### ISSUE TITLE
Investigate and implement LoRA

### ISSUE THREAD

**Issue by 0x000011b** [PygmalionAI/accelerate-training-code#3]
Basically, I want to find out whether we can:

- Fine-tune a 12B model with our current setup (4 RTX A6000s)
- Merge the weights back into the main model so it can be used within HF with no architectural changes

Suggestion: give [OpenDelta](https://github.com/thunlp/OpenDelta) a shot for the LoRA implementation. If that gets a 12B training without OOMing, look into how to collapse the adapter weights back into the original model as loaded by HF.

**Comment by TearGosling** [comment]
OpenDelta does not seem to be very compatible with HuggingFace architecture. I suggest instead (and I myself will be looking into) HuggingFace's [PEFT library](https://huggingface.co/blog/peft) or the library it's based on called [loralib](https://github.com/microsoft/lora).
